name: Sync with Upstream

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour, adjust the cron schedule as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Forked Repo
        uses: actions/checkout@v3
        with:
          repository: isabelle-pundix/FXSwap-TokenList
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/FunctionX-SG/FXSwap-TokenList.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main

      - name: Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
